POST http://127.0.0.1:8000/UsernamePost/
Content-Type:application/json

{
    "username":"username0",
    "password":"pass0",
    "email":"emaile@gmail.com"
}

###

GET http://127.0.0.1:8000/UsernameGet/

###

DELETE   http://127.0.0.1:8000/Usernamedelete/username0

###

POST http://127.0.0.1:8000/BlogPost/
Content-Type: application/json

{
    "title":"nothing",
    "text_data":"everythingo"
}

###
GET http://127.0.0.1:8000/BlogGet/