# Generated by Django 4.2.4 on 2023-10-08 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="users", name="username", field=models.TextField(unique=True),
        ),
    ]
