# Generated by Django 4.2.4 on 2023-10-08 12:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0002_alter_users_username"),
    ]

    operations = [
        migrations.RemoveField(model_name="bloginfo", name="text_id",),
    ]
